apiVersion : apps/v1
kind: Deployment
metadata:
  name: ioutility-adm-apresentacao-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ioutility-adm-apresentacao-service
  template:
    metadata:
      labels:
        app: ioutility-adm-apresentacao-service
    spec:
      containers:
        - name: utilityadmapresentacaoservice
          image: ioutilityimages.azurecr.io/ioutilityadmapresentacaoservice
          ports:
          - containerPort: 80
