apiVersion: v1
kind: Service
metadata:
    name: ioutility-adm-apresentacao-service
spec:
    type: LoadBalancer
    ports:
    - port: 80
    selector:
        app: ioutility-adm-apresentacao-service
