import { UF } from './models';
export const LISTA_ENDERECO_UFS: UF[] = [
  new UF("Acre", "AC"),
  new UF("Alagoas", "AL"),
  new UF("Amapá", "AP"),
  new UF("Amazonas", "AM"),
  new UF("Bahia", "BA"),
  new UF("Ceará", "CE"),
  new UF("Distrito Federal", "DF"),
  new UF("Espírito Santo", "ES"),
  new UF("Goiás", "GO"),
  new UF("Maranhão", "MA"),
  new UF("Mato Grosso", "MT"),
  new UF("Mato Grosso do Sul", "MS"),
  new UF("Minas Gerais", "MG"),
  new UF("Pará", "PA"),
  new UF("Paraíba", "PB"),
  new UF("Paraná", "PR"),
  new UF("Pernambuco", "PE"),
  new UF("Piauí", "PI"),
  new UF("Rio de Janeiro", "RJ"),
  new UF("Rio Grande do Norte", "RN"),
  new UF("Rio Grande do Sul", "RS"),
  new UF("Rondônia", "RO"),
  new UF("Roraima", "RR"),
  new UF("Santa Catarina", "SC"),
  new UF("São Paulo", "SP"),
  new UF("Sergipe", "SE"),
  new UF("Tocantins", "TO")
];
